variable "location" {}
variable "prefix" {}
variable "env" {}
variable "os_type" {}
variable "sku_name" {}
variable "dotnet_version" {}
variable "redisVersion" {}
variable "capacity" {}
variable "family" {}
variable "tier" {}
variable "non_ssl_port" {}
variable "pg_user" {}
variable "pg_pwd" {}
variable "psku_name" {}
variable "pg_ver" {}
variable "storage_mb" {}
variable "bkup_ret" {}
variable "Parent_Business" {}
variable "Enviornment" {}
variable "Portfolio" {}
variable "Service_Line" {}
variable "Service" {}
variable "Product" {}
#variable "storage_rg" {}
#variable "stg_act" {}
#variable "terraform_cont" {}
variable "vnet_address_space" {}
variable "ag_address_space" {}
variable "redis_address_space" {}
variable "pgsql_address_space" {}
variable "pvtendpt_address_space" {}