variable "location" {}
variable "prefix" {}
variable "env" {}
variable "resource_group_name" {}
variable "Parent_Business" {}
variable "Enviornment" {}
variable "Portfolio" {}
variable "Service_Line" {}
variable "Service" {}
variable "Product" {}
variable "vnet_address_space" {}
variable "ag_address_space" {}
variable "redis_address_space" {}
variable "pgsql_address_space" {}
variable "pvtendpt_address_space" {}